### ISSUE TITLE
logging broken

### ISSUE THREAD

**Issue by armijnhemel** [armijnhemel/binaryanalysis-ng#15]
The commit in 299da183086d37596160787bb7ad56cb8344fb8f seems to break logging.

**Comment by armijnhemel** [comment]
@timhemel when I print the value of uselogging in log() it says "None". Probably scoping?

**Comment by timhemel** [comment]
It is better to pass the logger and with it uselogging, as parameters to each process. This prevents that garbage collection in the parent process affects the other processes or something along those lines. But even better is to have each process log to its own file, this prevents the logfile being a bottleneck, and makes it easier to see what happens in each thread.

**Comment by armijnhemel** [comment]
perhaps rework according to the best practices here? https://docs.python.org/3/howto/logging.html

**Comment by timhemel** [comment]
Yes, and reading https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes suggest that each process should log to its own file.

**Comment by armijnhemel** [comment]
Confirmed that the fix works.
