### ISSUE TITLE
ScanJobError does not have a "filename" attribute

### ISSUE THREAD

**Issue by armijnhemel** [armijnhemel/binaryanalysis-ng#16]
printing a ScanJobError fails:

AttributeError: 'ScanJob' object has no attribute 'filename'

@timhemel what did you exactly have in mind with ScanJobError?

**Comment by armijnhemel** [comment]
Simple test case to force this error: return None in an unpacker function

**Comment by timhemel** [comment]
ScanJobError is a wrapper exception class, if an exception is caught, the original stacktrace is shown, but with it is the filename and the labels. The idea was to get better error feedback during manual tests.

**Comment by armijnhemel** [comment]
> ScanJobError is a wrapper exception class, if an exception is caught, the original stacktrace is shown, but with it is the filename and the labels. The idea was to get better error feedback during manual tests.

OK, so it seems that sometimes the filename is missing.

**Comment by timhemel** [comment]
FIxed just now.

**Comment by armijnhemel** [comment]
A few other things were missing, fixed now.
