### ISSUE TITLE
MBR image not properly detected (no unpacker?)

### ISSUE THREAD

**Issue by timhemel** [armijnhemel/binaryanalysis-ng#22]
My test file `openwrt-18.06.1-brcm2708-bcm2710-rpi-3-ext4-sysupgrade.img.gz` contains an image, which `file` identifies as MBR image:
```
$ file openwrt-18.06.1-brcm2708-bcm2710-rpi-3-ext4-sysupgrade.img
openwrt-18.06.1-brcm2708-bcm2710-rpi-3-ext4-sysupgrade.img: DOS/MBR boot sector; partition 1 : ID=0xc, active, start-CHS (0x20,2,3), end-CHS (0xc3,0,12), startsector 8192, 40960 sectors; partition 2 : ID=0x83, start-CHS (0xe3,2,15), end-CHS (0x14,0,16), startsector 57344, 524288 sectors
```

Bang does not find it. It mistakenly identifies a FAT filesystem because it recognizes the magic number for MBR `\x55\xaa`. As a result, bang is trying many other filetypes and clutters the unpack directory.

There should be an unpacker for MBR images.

**Comment by armijnhemel** [comment]
Correct, there is no unpacker for MBR yet.

**Comment by timhemel** [comment]
Made one with kaitai-struct, still needs integration.

**Comment by timhemel** [comment]
kaitai parser for this merged in master branch, closing this issue.
