### ISSUE TITLE
TypeError: invalid file: PosixPath('/root/tmp/bang-scan-r42t3f24/STARTED')

### ISSUE THREAD

**Issue by wxh0000mm** [armijnhemel/binaryanalysis-ng#27]
HI
I run bang-scanner for an error

root@ubuntu:/home/test/binaryanalysis-ng/src# python3 bang-scanner -c bang.config -f /home/test/Desktop/S29AL016D90-200000H.bin
Traceback (most recent call last):
  File "bang-scanner", line 403, in <module>
    main(sys.argv)
  File "bang-scanner", line 168, in main
    startedfile = open(scandirectory / "STARTED", 'wb')
TypeError: invalid file: PosixPath('/root/tmp/bang-scan-r42t3f24/STARTED')
root@ubuntu:/home/test/binaryanalysis-ng/src#

**Comment by armijnhemel** [comment]
That should not happen. Could you tell me which version of Ubuntu you are using so I can try to replicate? Also, can you tell me where I can get "S29AL016D90-200000H.bin" so I can try to reproduce?

**Comment by armijnhemel** [comment]
OK, I can reproduce a similar error on Fedora. I will work on this. Thank you for reporting.

**Comment by wxh0000mm** [comment]
![image](https://user-images.githubusercontent.com/24783964/61280363-51519e00-a7ea-11e9-9094-3cec32a0ac3c.png)

**Comment by wxh0000mm** [comment]
S29al016d90-200000h. bin this file is just a normal bin file

**Comment by armijnhemel** [comment]
In the standard configuration file it says:

baseunpackdirectory = %(HOME)s/tmp

Did you create a directory "tmp" in your home directory?

**Comment by wxh0000mm** [comment]
Yes, I did create a TMP directory

**Comment by armijnhemel** [comment]
Do you get the same error when running as a normal user and/or using for example /tmp as the path? If so, it must be related to the file you are scanning and there is some other bug. Can you tell me where I could get it?

**Comment by wxh0000mm** [comment]
I can give you this BIN file, can you leave a email?

**Comment by wxh0000mm** [comment]
[S29AL016D90-200000H.zip](https://github.com/armijnhemel/binaryanalysis-ng/files/3396315/S29AL016D90-200000H.zip)

**Comment by armijnhemel** [comment]
thanks, I have the file, will analyse

**Comment by armijnhemel** [comment]
I can unpack it perfectly fine on Fedora, so my guess is a missing dependency. I will investigate this further tonight.

**Comment by wxh0000mm** [comment]
thanks


| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 17:36, Armijn Hemel wrote:

I can unpack it perfectly fine on Fedora, so my guess is a missing dependency. I will investigate this further tonight.

**Comment by wxh0000mm** [comment]
I did an experiment
Use BINWALK to unzip a router firmware that can be unpacked
Use BANG to error


| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 17:36, Armijn Hemel wrote:

I can unpack it perfectly fine on Fedora, so my guess is a missing dependency. I will investigate this further tonight.

**Comment by armijnhemel** [comment]
My guess is that you are missing a dependency on Ubuntu, so I will document which packages need to be installed.

I regularly do a smoke test with a few thousand firmware files to test for regressions, but I do these on Fedora. I will start doing more tests on Ubuntu as well.

**Comment by armijnhemel** [comment]
I was able to reproduce this bug on Ubuntu 16.04. Currently investigating.

**Comment by wxh0000mm** [comment]
I'm using Ubuntu 16.04 64



| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 21:16, Armijn Hemel wrote:

I was able to reproduce this bug on Ubuntu 16.04. Currently investigating.

**Comment by armijnhemel** [comment]
OK, found the cause: Python 3 on Ubuntu is too old (3.5.2), which means that certain functionality from the pathlib module is not available. The requirements actually say: python 3.6 or higher. So, this is not a bug, your distribution is simply too old.

**Comment by wxh0000mm** [comment]
What is your version of python3? I also had this problem when I upgraded my python 3 to 3.6



| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 21:34, Armijn Hemel wrote:

OK, found the cause: Python 3 on Ubuntu is too old (3.5.2), which means that certain functionality from the pathlib module is not available. The requirements actually say: python 3.6 or higher. So, this is not a bug, your distribution is simply too old.

**Comment by armijnhemel** [comment]
Currently 3.7.3, but it really should work with 3.6 and later. I will also retry with an Ubuntu 18.04.

**Comment by wxh0000mm** [comment]
I'll try upgrading python3 to version 3.7



| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 21:40, 王旭辉 wrote:
What is your version of python3? I also had this problem when I upgraded my python 3 to 3.6



| |
王旭辉
邮箱：wxh0000mm@163.com
|

签名由 网易邮箱大师 定制

On 07/16/2019 21:34, Armijn Hemel wrote:

OK, found the cause: Python 3 on Ubuntu is too old (3.5.2), which means that certain functionality from the pathlib module is not available. The requirements actually say: python 3.6 or higher. So, this is not a bug, your distribution is simply too old.

**Comment by armijnhemel** [comment]
If you bump into problems just reopen this bug.
