### ISSUE TITLE
nix-shell error

### ISSUE THREAD

**Issue by davidak** [armijnhemel/binaryanalysis-ng#29]
```
[davidak@ethmoid:~/code/binaryanalysis-ng]$ nix-shell 
error: undefined variable 'dockerfile-parse' at /home/davidak/code/binaryanalysis-ng/shell.nix:6:5
(use '--show-trace' to show detailed location information)
```
On which channel are you on?

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.49, NixOS, 19.03.172866.4649b6ef4b5 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172979.8634c3b6199, nixos-hardware, nixos-unstable-19.09pre183392.83ba5afcc96"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by armijnhemel** [comment]
adding @zimbatm as he added the Nix file and can clarify.

**Comment by davidak** [comment]
I get no error with the unstable channel:

`nix-shell -I nixpkgs=https://releases.nixos.org/nixos/unstable/nixos-19.09pre185259.362be9608c3/nixexprs.tar.xz
`

But running it don't work as described in the readme:

```
[nix-shell:~/code/binaryanalysis-ng]$ python3 bang-scanner -f ~/promo-greenbone-8GB-2.gz
/nix/store/7q2pgxz0yhf8b3dywq67x5m41gmhsagh-python3-3.7.3/bin/python3: can't open file 'bang-scanner': [Errno 2] No such file or directory
```

Install instructions and proper packaging should fix that.

**Comment by zimbatm** [comment]
I guess we should pin the version of nixpkgs. @armijnhemel do you mind if I add a nix/ folder in the project top-level?

**Comment by armijnhemel** [comment]
> I guess we should pin the version of nixpkgs. @armijnhemel do you mind if I add a nix/ folder in the project top-level?

No, not at all. I am planning to cut a 0.1 soonish.
