### ISSUE TITLE
VxWorks support

### ISSUE THREAD

**Issue by brainstorm** [armijnhemel/binaryanalysis-ng#31]
After cloning today from `master` and building the Docker container:

```
$ docker build -t bang
(...)
  python3-pytz-2018.5-1.fc29.noarch
  python3-webencodings-0.5.1-6.fc29.noarch
  yajl-2.1.0-11.fc29.x86_64

Complete!
Removing intermediate container 727e3b8f8134
 ---> 798710dfd0fb
Step 5/5 : CMD ["python3","bangshell"]
 ---> Running in de71b6f2177b
Removing intermediate container de71b6f2177b
 ---> eceae9b2e1dc
Successfully built eceae9b2e1dc
Successfully tagged bang:latest
```

Then inside the container itself interactively, `bang-scanner` does not seem to behave as specified in the [README.md's invocation](https://github.com/armijnhemel/binaryanalysis-ng#invocation):

```
$ docker run -it bang /bin/bash
[root@b6cc367e62c7 bang]# ./src/bang-scanner
bash: ./src/bang-scanner: Permission denied
[root@b6cc367e62c7 src]# chmod +x bang-scanner
[root@b6cc367e62c7 src]# ./bang-scanner
Traceback (most recent call last):
  File "./bang-scanner", line 52, in <module>
    import elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
```

**Comment by armijnhemel** [comment]
Apologies, the Dockerfile is currently not well maintained (and needs more love). I have fixed the dependency issue in 8674131aea9177423f2dac1915b9bdb434f899f6

The entry point for the Dockerfile is also wrong, I still need to look into that.

**Comment by brainstorm** [comment]
Hey, no worries, really appreciate the celerity of your answer and fix, thanks! :)

I guess that what you're after is sth like this?:

```diff
diff --git a/Dockerfile b/Dockerfile
index 021c50d..5202736 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -34,4 +34,6 @@ RUN dnf update -y && \
                    util-linux \
                    zstd

-CMD ["python3","bangshell"]
+RUN chmod +x bang-scanner
+
+CMD ["./bang-scanner", "-d", "/mnt/input", "-u", "/mnt/output"]
```

I've just run it like so:

```bash
$ docker run -v VxWorks.bin:/mnt/input/VxWorks.bin -v /tmp:/mnt/tmp -v output:/mnt/output bang
```

Also using the `file` flag instead of the `dir` one inside an interactive container session:

```bash
./bang-scanner -f /mnt/input/VxWorks.bin -t /mnt/tmp -u /mnt/output
```

But the results are a bit underwhelming for my input file, unfortunately :_/ I might be doing something wrong here?

I am attach the (zip-compressed) input file here just in case you want to test it out yourself a bit and perhaps add more carving functionality ;)

[VxWorks.bin.zip](https://github.com/armijnhemel/binaryanalysis-ng/files/3422174/VxWorks.bin.zip)

**Comment by brainstorm** [comment]
More context on why it is a bit underwhelming (from `report.txt`):

```
SCAN RESULTS FOR: /mnt/input/VxWorks.bin"
Start: 2019-07-23T13:12:58.404144
Stop: 2019-07-23T13:13:19.742314
Duration (seconds): 21.33817

File: VxWorks.bin
=================

MD5: 3e25c877e25afa75b3f58e1bdf9a0dc6
SHA256: 066bf57cd8c8761c1fa3019841634450cf8f323fc35889dff8fae1d3bb20ad8a
Size: 12411552
MIME type: application/octet-stream
Labels: binary, root
Bytes identified: 0 (0.000000 %)

Total labels:
=============
Name: root
Amount: 1
Name: binary
Amount: 1
```

Not much inside the pickles either:

```
$ ls -alh results/
total 8
drwxr-xr-x  3 romanvg  staff    96B Jul 23 23:13 .
drwx------  8 romanvg  staff   256B Jul 23 23:13 ..
-rw-r--r--  1 romanvg  staff   329B Jul 23 23:13 066bf57cd8c8761c1fa3019841634450cf8f323fc35889dff8fae1d3bb20ad8a.pickle
```

And the logs show many attempts to identify `.ico` and `.jpeg` files? Among other failed attempts:

```
TRYING VxWorks.bin jpeg at offset: 12146659
FAIL VxWorks.bin jpeg at offset: 12146659: invalid value for start of frame
TRYING VxWorks.bin jpeg at offset: 12153775
FAIL VxWorks.bin jpeg at offset: 12153775: invalid value for start of frame
TRYING VxWorks.bin ico at offset: 12173482
FAIL VxWorks.bin ico at offset: 12173482: wrong offset for image data
TRYING VxWorks.bin jpeg at offset: 12196191
FAIL VxWorks.bin jpeg at offset: 12196191: invalid value for start of frame
TRYING VxWorks.bin pbm at offset: 12246753
FAIL VxWorks.bin pbm at offset: 12246753: no integer in header
TRYING VxWorks.bin ppm at offset: 12254076
FAIL VxWorks.bin ppm at offset: 12254076: no whitespace in header
TRYING VxWorks.bin pgm at offset: 12284860
FAIL VxWorks.bin pgm at offset: 12284860: no whitespace in header
TRYING VxWorks.bin pbm at offset: 12285036
FAIL VxWorks.bin pbm at offset: 12285036: no whitespace in header
TRYING VxWorks.bin fat at offset: 12328687
FAIL VxWorks.bin fat at offset: 12328687: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328703
FAIL VxWorks.bin fat at offset: 12328703: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328719
FAIL VxWorks.bin fat at offset: 12328719: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328735
FAIL VxWorks.bin fat at offset: 12328735: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328751
FAIL VxWorks.bin fat at offset: 12328751: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328767
FAIL VxWorks.bin fat at offset: 12328767: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328783
FAIL VxWorks.bin fat at offset: 12328783: invalid jump instruction
TRYING VxWorks.bin fat at offset: 12328799
```

The architecture of the `.bin` is [SuperH4](https://en.wikipedia.org/wiki/SuperH), perhaps it is a bit too much to ask in terms of detection/unpacking of signatures? ;)

**Comment by armijnhemel** [comment]
It tries to find a structure in the file and it seems that it cannot find any. The signatures for ico and jpeg are very generic, so there are always many false tries.

I would need to look into the structure of VxWorks binaries and add support for that. I will search for a public specification (no leaked docs), but I am a bit pessimistic about my chances of finding one.

I looked into the file and there doesn't seem to be any obvious compression used. I looked into what binwalk could detect but it seems they can't detect much either.

**Comment by brainstorm** [comment]
That's accurate, that's why I moved away from binwalk which generates a ton of false positives and hoped for binaryanalysis-ng to be able to crack this nut:

http://www.devttys0.com/2011/07/reverse-engineering-vxworks-firmware-wrt54gv8/

**Comment by armijnhemel** [comment]
Currently I am mostly focusing on embedded Linux and Java, but I have found some papers that might get me some further with this, but I still have to read them. Have you checked out radare2 for this?

**Comment by brainstorm** [comment]
[Yep, I have been dabbling with r2 for a while :)](https://github.com/radare/radare2/issues?utf8=%E2%9C%93&q=brainstorm)

After a few quick searches I found some interesting VxWorks-related resources:

https://www.secniche.org/vxworks/vxworks_os_holistic_security_adityaks.pdf  (section 8.1)
https://wikileaks.org/ciav7p1/cms/page_16384164.html  (Binwalk detecting some VxWorks symbol tables)

Would you mind sharing those papers you found over here? Let's see how far we can run with this ;)

**Comment by brainstorm** [comment]
Heh, so conveniently timed:

https://go.armis.com/hubfs/White-papers/Urgent11%20Technical%20White%20Paper.pdf

I wish @armissecurity were a bit more verbose about the unpacking of VxWorks firmware so that we don't have to cook it ourselves :)

**Comment by armijnhemel** [comment]
> [Yep, I have been dabbling with r2 for a while :)](https://github.com/radare/radare2/issues?utf8=%E2%9C%93&q=brainstorm)
> 
> After a few quick searches I found some interesting VxWorks-related resources:
> 
> https://www.secniche.org/vxworks/vxworks_os_holistic_security_adityaks.pdf (section 8.1)
> https://wikileaks.org/ciav7p1/cms/page_16384164.html (Binwalk detecting some VxWorks symbol tables)
> 
> Would you mind sharing those papers you found over here? Let's see how far we can run with this ;)

https://www.blackhat.com/presentations/bh-usa-07/Maynor_and_Graham/Whitepaper/bh-usa-07-maynor_and_graham-WP.pdf

and a forum:

http://www.openrce.org/forums/posts/1212

I haven't had time to dig into this though.

**Comment by brainstorm** [comment]
This is quite spot on, really nice talk from this year's Black Hat Asia:

https://i.blackhat.com/asia-19/Fri-March-29/bh-asia-Zhu-Dive-into-VxWorks-Based-IoT-Device-Debug-the-Undebugable-Device.pdf

The underlying tooling (GHidra plugin) can be used in your project, I reckon.

**Comment by armijnhemel** [comment]
Thanks! I will look into this soon (currently traveling)

**Comment by brainstorm** [comment]
Fixed by using radare2 and vxHunter: https://github.com/PAGalaxyLab/vxhunter
See: https://github.com/PAGalaxyLab/vxhunter/commit/a04849ee5401cac39b8aa71d6ce3680ec47998f1
