### ISSUE TITLE
Any usage?

### ISSUE THREAD

**Issue by true-zk** [armijnhemel/binaryanalysis-ng#343]
what should I do after nix-shell is ready? 

When I run "python3 -m bang.cli scan -u xxx xxx", It shows error: Error while finding module specification for 'bang.cli' (ModuleNotFoundError: No module named 'bang')

**Comment by armijnhemel** [comment]
Thank you for your report. I am still refactoring the repository, so not everything is there yet including some of the documentation, for which I apologize. I have added some more instructions to `README.md` that should help.

**Comment by true-zk** [comment]
Wow, thanks for ur response. It works.
