### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by AnotherWayIn** [armijnhemel/binaryanalysis-ng#351]
I've just been through the nix setup (ubuntu 23.04) and now at the stage of running for the first time, but i get the below error:

Are you able to expand on the usage info as there isn't much on the readme?
maybe some more examples or a yt video

thanks

```

[nix-shell:~/tools/binaryanalysis-ng]$ python3 -m bang.cli     
/nix/store/4agknr9yslk6rd1n5s45pgxlmpfb4vvq-python3-3.10.11-env/bin/python3.10: Error while finding module specification for 'bang.cli' (ModuleNotFoundError: No module named 'bang')
```

**Comment by armijnhemel** [comment]
> I've just been through the nix setup (ubuntu 23.04) and now at the stage of running for the first time, but i get the below error:
> 
> Are you able to expand on the usage info as there isn't much on the readme? maybe some more examples or a yt video
> 
> thanks
> 
> ```
> 
> [nix-shell:~/tools/binaryanalysis-ng]$ python3 -m bang.cli     
> /nix/store/4agknr9yslk6rd1n5s45pgxlmpfb4vvq-python3-3.10.11-env/bin/python3.10: Error while finding module specification for 'bang.cli' (ModuleNotFoundError: No module named 'bang')
> ```

I will work a bit on the README. The missing step here is to first do a `cd src`.

**Comment by AnotherWayIn** [comment]
ah that was all. thanks for the quick reply :)
