### ISSUE TITLE
program hung ( not response over 1 hour )

### ISSUE THREAD

**Issue by Ku100vEvgen** [armijnhemel/binaryanalysis-ng#36]
I'm trying a program to explore the possibilities of scanning

[kea@localhost src]$ python3 ./bang-scanner -c ./bang.config -f ./openwrt-realtek-A2004NS-AP-fw_SDK_v2.4_20150724_release_by_Igor_T.bin

and program hung ( not response over 1 hour )

if interested, then this file https://cloud.mail.ru/public/3snL/3gnzzsBGx

**Comment by armijnhemel** [comment]
I cannot reproduce this error (and it finishes unpacking within a few seconds). Can you describe your environment (linux distribution, etc.)?

**Comment by Ku100vEvgen** [comment]
$python3 --version
Python 3.6.8

$lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

$arch
x86_64

**Comment by armijnhemel** [comment]
Very strange, I will try on 18.04 soon. It could be a difference in the compression methods supported in "unsquashfs".
