### ISSUE TITLE
creates a file of infinite size

### ISSUE THREAD

**Issue by Ku100vEvgen** [armijnhemel/binaryanalysis-ng#37]
I'm trying a program to explore the possibilities of scanning

[kea@localhost src]$ python3 ./bang-scanner -c ./bang.config -f ./fw-UR-825AC-12.11.15.bin

the program creates a file of infinite size ( I interrupted on a file size "sda" of 100GB )
bang-scan-ejl4sdbz/unpack/fw-UR-825AC-12.11.15.bin-0x0014c822-squashfs-1/dev/sda

if interested, then this file https://cloud.mail.ru/public/481V/5kbYd9dLz

**Comment by armijnhemel** [comment]
I cannot reproduce this error either. I am very surprised that it is trying to write the dev/sda file from the squashfs file system. It should not do that. Does your user "kea" perhaps have sudo rights? Could you send the output of "ls -l" for the dev/sda file, plus the output of "unsquashfs -v"?

My guess that it is something in the unsquashfs program itself that might be going wrong.
