### ISSUE TITLE
Bang get stucked as <defunct> after one of the jobs failed to create symlinks

### ISSUE THREAD

**Issue by hhao020** [armijnhemel/binaryanalysis-ng#371]
This happens when I'm using a windows share folder as the unpack path. Bang stucked when it tries to create a symlink, as symlink is not supported by Windows. It seems like all threads are in barrier waiting.

Other exceptions can cause the same issue. Without "-j' parameter, Bang works well and can properly handle exceptions.

[without-verbose.log](https://github.com/armijnhemel/binaryanalysis-ng/files/13539151/without-verbose.log)
[with-verbose.log](https://github.com/armijnhemel/binaryanalysis-ng/files/13539154/with-verbose.log)

**Comment by armijnhemel** [comment]
Thanks for the report. I am not so sure how to tackle this apart from "don't write to a Windows share". Let me think about it. In the meantime I will add a warning to the documentation.

**Comment by hhao020** [comment]
The problem can be reproduced: 
1, a folder on a ntfs disk to extract to;
2, symbol links to create;
3, jobs > 1
Since it won't happen on EXT disks, we can close this issue.
