### ISSUE TITLE
Strings in .jar are splitted unexpectedly

### ISSUE THREAD

**Issue by hhao020** [armijnhemel/binaryanalysis-ng#372]
The problem was seen in parsing jar packages. For example, in gson (by google), strings in JsonParser.class should like below:
`strings gson-2.2.2/root/_rel/com/google/gson/JsonParser.class
.........
$Did not consume the entire document.
.........
Failed parsing JSON source:
 to Json
java/lang/OutOfMemoryError
com/google/gson/JsonParser
`
**However, BANG gives below result. This takes trouble to use them.**
`'00d0e1af346abe733d8ba8f6f88ca203c33eb7857f8aaea78f67b7d36d7f714b':
   {'metadata': {'hashes': {'sha256': '00d0e1af346abe733d8ba8f6f88ca203c33eb7857f8aaea78f67b7d36d7f714b',
                                                                                              'md5': '1f85c49d4138a42466ac6d964cfd2db5',
                                                                                              'sha1': '61b79592df19ca3e3464e4adcd39908fc9f75877',},
                                                                                   'strings': ['Did '
                                                                                               'not '
                                                                                               'consume '
                                                                                               'the '
                                                                                               'entire '
                                                                                               'document.',
                                                                                               'Failed '
                                                                                               'parsing '
                                                                                               'JSON '
                                                                                               'source: ',
                                                                                               ' '
                                                                                               'to '
                                                                                               'Json'],
                                                                                   'classname': 'com/google/gson/JsonParser',
                                                                      'filepath': PosixPath('root/_rel/com/google/gson/JsonParser.class')},`

**Comment by armijnhemel** [comment]
> Do you have the corresponding source code so I can compare?

Never mind:

https://github.com/google/gson/blob/main/gson/src/main/java/com/google/gson/JsonParser.java

**Comment by armijnhemel** [comment]
I cannot reproduce the problem. With the latest BANG I am seeing:

```
{'metadata': {'hashes': {'sha256': '00d0e1af346abe733d8ba8f6f88ca203c33eb7857f8aaea78f67b7d36d7f714b', 'md5': '1f85c49d4138a42466ac6d964cfd2db5', 'sha1': '61b79592df19ca3e3464e4adcd39908fc9f75877', 'tlsh': 'T155514087F01095C7F45FE97E19640B5479F098382317B911CF03885A67EBA55DD6A1F0'}, 'flags': {'public': True, 'final': True, 'super': True, 'interface': False, 'abstract': False, 'synthetic': False, 'annotation': False, 'enum': False, 'module': False}, 'strings': ['Did not consume the entire document.', 'Failed parsing JSON source: ', ' to Json'], 'classname': 'com/google/gson/JsonParser', 'fields': [], 'methods': ['<init>', 'parse', 'parse', 'parse'], 'sourcefile': 'JsonParser.java'}, 'unpack_parser': 'javaclass', 'size': 2594, 'labels': ['java class']}
```

Which Git commit are you on?

**Comment by hhao020** [comment]
I will try the latest code from Git.

**Comment by hhao020** [comment]
It's not a bug. I missed commas/spaces between those words. Pprint.pp are used to print those .pkl information to a text file. Then strings in multiple lines are printed in lines. For example, 'JsonReader is closed' was converted to:
'JsonReader '
'is '
'closed',
However there's no commas between the above words. That means it's still a 3-word string, but not 3 strings. It's strange why it outputs like this.

Sorry for any inconvenience.
