### ISSUE TITLE
No module named 'ahocorasick

### ISSUE THREAD

**Issue by lYlantis** [armijnhemel/binaryanalysis-ng#377]
I followed the instructions on [getting started ](https://github.com/armijnhemel/binaryanalysis-ng?tab=readme-ov-file#getting-started), went to run bang.

```bash
python3 -m bang.cli scan -u ../test-bang/ ../../test-binaries/demo.bin
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/$USER/unpacking/binaryanalysis-ng/src/bang/cli.py", line 50, in <module>
    from .scan_environment import *
  File "/home/$USER/unpacking/binaryanalysis-ng/src/bang/scan_environment.py", line 29, in <module>
    import ahocorasick
ModuleNotFoundError: No module named 'ahocorasick'
```

**Comment by armijnhemel** [comment]
Did you install the dependencies using Nix?

**Comment by armijnhemel** [comment]
I just tried on a fresh install and when the dependencies are installed with nix, then it works.

**Comment by lYlantis** [comment]
I did do it with nix. I think I see what I did now though. I tried to run that command outside of the nix-shell. When running it in the nix-shell, it does successfully extract the binary. Thanks for the help!

**Comment by lYlantis** [comment]
Is anything besides scan supported?

I tried running print-tree, report and show on the output directory of scan

```bash
python3 -m bang.cli show /home/$USER/unpacking/binaryanalysis-ng/test-bang/t2
```

They all return directory not found. I pasted the output of pwd as the path.

**Comment by armijnhemel** [comment]
> Is anything besides scan supported?
> 
> I tried running print-tree, report and show on the output directory of scan
> 
> ```shell
> python3 -m bang.cli show /home/$USER/unpacking/binaryanalysis-ng/test-bang/t2
> ```

Try adding the name of a directory, such as `root`. I need to clarify that in the documentation.

**Comment by lYlantis** [comment]
Sorry, not sure I understand. If I try to add anything to that command, it returns with unexpected argument. The path that is there is the full absolute path. Can you give me an example of what a correct command would be?

**Comment by armijnhemel** [comment]
> Sorry, not sure I understand. If I try to add anything to that command, it returns with unexpected argument. The path that is there is the full absolute path. Can you give me an example of what a correct command would be?

```
python3 -m bang.cli show /home/$USER/unpacking/binaryanalysis-ng/test-bang/t2/root
```

(if that directory exists). The unpacking structure of BANG is a little bit complicated. It makes sense if you understand the reasons behind it, but there is a steeper learning curve. I will work on better documentation, and also on tools to more easily navigate the unpacking structure, but this will take some time.

**Comment by lYlantis** [comment]
Okay, I get it now and got the commands working. Thanks so much for the assistance!
