### ISSUE TITLE
name counter does not work correctly for concatenated files having the "right" extension

### ISSUE THREAD

**Issue by armijnhemel** [armijnhemel/binaryanalysis-ng#76]
Example: two GIF files concatenated together:

```
test.gif-0x00000000-gif-1/unpacked.gif
test.gif-0x000351b5-gif-1/unpacked.gif
```
The counter should have been increased.

**Comment by armijnhemel** [comment]
If I rename the file 'test.gif' to 'test.gaf' it works correctly:

```
test.gaf-0x00000000-gif-1/unpacked.gif
test.gaf-0x000351b5-gif-2/unpacked.gif
```

**Comment by timhemel** [comment]
Added `test_double_gif_file_increases_name_counter` in `test_scan_job.py` to test for this.

**Comment by armijnhemel** [comment]
no longer relevant in the new unpacking structure
