### ISSUE TITLE
new scanjob cannot process broken symbolic links

### ISSUE THREAD

**Issue by armijnhemel** [armijnhemel/binaryanalysis-ng#8]
The new scanjob setup has a problem with broken links:

$ time python3 bang-scanner -c bang.config -f /tmp/TEW-636APB-1002.bin 
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "bang-scanner", line 1120, in processfile
    scanjob.check_for_signatures(unpacker, fileresult, scanfilequeue, scanenvironment, unpackdirectory, temporarydirectory)
  File "bang-scanner", line 378, in check_for_signatures
    j = ScanJob(pathlib.Path(unpackedfile), unpackedlabel, self.filename, [], {})
  File "bang-scanner", line 107, in __init__
    self._stat_file()
  File "bang-scanner", line 119, in _stat_file
    self.stat = os.stat(self.filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/armijn/tmp/bang-scan-2dchgsnf/unpack/TEW-636APB-1002.bin-squashfs-1/usr/sbin/rc'

This file is a broken symlink.

The init() method of the ScanJob class calls self.stat_file() which throws an exception.

**Comment by armijnhemel** [comment]
@timhemel could you take a look to see how this can be fixed?

**Comment by armijnhemel** [comment]
dirty workaround in 9466010ece06f195b767efd11609cf3e1327f36e

**Comment by timhemel** [comment]
Fix in branch issue-8
